### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by erei** [CoeBotWiki/wiki#1]
Some things need to change with the wiki, most notably:

- [x] I need to make use of mkdocs' styling in the YAML configuration instead of overriding it with CSS, luckily, the theme we use has a theme color very similar to the CoeBot green.
- [ ] I need to rewrite the usage for a lot of commands, they're bad.
- [ ] The right scrolling sidebar needs some reformatting. e.g. make use of prefix
- [ ] Move some extraneous pages to either the GitHub repository or scrap them all together.
- [ ] Automate deployment to the site repository.

- [x] Redo general commands.
- [ ] Redo custom commands.
- [x] Redo fun commands.
- [ ] Redo moderation commands.
- [ ] Redo filters.
- [ ] Redo strings.
- [x] Redo admin.
